package main

import (
    "fmt"
    "encoding/json"
)
const (
jsonStuff = `{
  "apPropertyBlock": {
    "bpWiredMacaddr": "00:04:96:97:E9:EE",
    "ruModel": "X460G2-24t-10G4",
    "ruSerialNumber": "1405G-00125",
    "ruSwVersion": "22.6.0.20"
  },
  "deviceInfo": {
    "firmwareRevision": "22.6.0.20",
    "ifTable": [
      {
        "dot1dBasePortIfIndex": 1001,
        "ifAdminStatus": 1,
        "ifDescr": "1",
        "ifInDiscards": 0,
        "ifInErrors": 0,
        "ifInNUcastPkts": 100896,
        "ifInOctets": 14066874,
        "ifInUcastPkts": 6523,
        "ifInUnknownProtos": 0,
        "ifIndex": 1001,
        "ifLastChange": 4000,
        "ifMtu": 1500,
        "ifName": "1",
        "ifOperStatus": 1,
        "ifOutDiscards": 0,
        "ifOutErrors": 0,
        "ifOutNUcastPkts": 6310,
        "ifOutOctets": 2485212,
        "ifOutQLen": 0,
        "ifOutUcastPkts": 6757,
        "ifPhysAddress": "00:04:96:97:e9:ee",
        "ifSpecific": "1.3.6.1",
        "ifSpeed": 1000000000,
        "ifType": 6
      },
      {
        "dot1dBasePortIfIndex": 1002,
        "ifAdminStatus": 1,
        "ifDescr": "2",
        "ifInDiscards": 0,
        "ifInErrors": 0,
        "ifInNUcastPkts": 100896,
        "ifInOctets": 14092516,
        "ifInUcastPkts": 6638,
        "ifInUnknownProtos": 0,
        "ifIndex": 1002,
        "ifLastChange": 4000,
        "ifMtu": 1500,
        "ifName": "2",
        "ifOperStatus": 1,
        "ifOutDiscards": 0,
        "ifOutErrors": 0,
        "ifOutNUcastPkts": 6306,
        "ifOutOctets": 2407723,
        "ifOutQLen": 0,
        "ifOutUcastPkts": 6413,
        "ifPhysAddress": "00:04:96:97:e9:ee",
        "ifSpecific": "1.3.6.1",
        "ifSpeed": 1000000000,
        "ifType": 6
      },
      {
        "dot1dBasePortIfIndex": 1003,
        "ifAdminStatus": 1,
        "ifDescr": "3",
        "ifInDiscards": 0,
        "ifInErrors": 0,
        "ifInNUcastPkts": 100897,
        "ifInOctets": 14119248,
        "ifInUcastPkts": 6756,
        "ifInUnknownProtos": 0,
        "ifIndex": 1003,
        "ifLastChange": 4000,
        "ifMtu": 1500,
        "ifName": "3",
        "ifOperStatus": 1,
        "ifOutDiscards": 0,
        "ifOutErrors": 0,
        "ifOutNUcastPkts": 6310,
        "ifOutOctets": 2458391,
        "ifOutQLen": 0,
        "ifOutUcastPkts": 6637,
        "ifPhysAddress": "00:04:96:97:e9:ee",
        "ifSpecific": "1.3.6.1",
        "ifSpeed": 1000000000,
        "ifType": 6
      },
      {
        "dot1dBasePortIfIndex": 1004,
        "ifAdminStatus": 1,
        "ifDescr": "4",
        "ifInDiscards": 0,
        "ifInErrors": 0,
        "ifInNUcastPkts": 100894,
        "ifInOctets": 14017454,
        "ifInUcastPkts": 6304,
        "ifInUnknownProtos": 0,
        "ifIndex": 1004,
        "ifLastChange": 4000,
        "ifMtu": 1500,
        "ifName": "4",
        "ifOperStatus": 1,
        "ifOutDiscards": 0,
        "ifOutErrors": 0,
        "ifOutNUcastPkts": 6306,
        "ifOutOctets": 2457793,
        "ifOutQLen": 0,
        "ifOutUcastPkts": 6636,
        "ifPhysAddress": "00:04:96:97:e9:ee",
        "ifSpecific": "1.3.6.1",
        "ifSpeed": 1000000000,
        "ifType": 6
      },
      {
        "dot1dBasePortIfIndex": 1005,
        "ifAdminStatus": 1,
        "ifDescr": "5",
        "ifInDiscards": 0,
        "ifInErrors": 0,
        "ifInNUcastPkts": 100896,
        "ifInOctets": 14066874,
        "ifInUcastPkts": 6523,
        "ifInUnknownProtos": 0,
        "ifIndex": 1005,
        "ifLastChange": 4000,
        "ifMtu": 1500,
        "ifName": "5",
        "ifOperStatus": 1,
        "ifOutDiscards": 0,
        "ifOutErrors": 0,
        "ifOutNUcastPkts": 6306,
        "ifOutOctets": 2407829,
        "ifOutQLen": 0,
        "ifOutUcastPkts": 6414,
        "ifPhysAddress": "00:04:96:97:e9:ee",
        "ifSpecific": "1.3.6.1",
        "ifSpeed": 1000000000,
        "ifType": 6
      },
      {
        "dot1dBasePortIfIndex": 1006,
        "ifAdminStatus": 1,
        "ifDescr": "6",
        "ifInDiscards": 0,
        "ifInErrors": 0,
        "ifInNUcastPkts": 100896,
        "ifInOctets": 14092410,
        "ifInUcastPkts": 6637,
        "ifInUnknownProtos": 0,
        "ifIndex": 1006,
        "ifLastChange": 4000,
        "ifMtu": 1500,
        "ifName": "6",
        "ifOperStatus": 1,
        "ifOutDiscards": 0,
        "ifOutErrors": 0,
        "ifOutNUcastPkts": 6306,
        "ifOutOctets": 2432469,
        "ifOutQLen": 0,
        "ifOutUcastPkts": 6524,
        "ifPhysAddress": "00:04:96:97:e9:ee",
        "ifSpecific": "1.3.6.1",
        "ifSpeed": 1000000000,
        "ifType": 6
      },
      {
        "dot1dBasePortIfIndex": 1007,
        "ifAdminStatus": 1,
        "ifDescr": "7",
        "ifInDiscards": 0,
        "ifInErrors": 0,
        "ifInNUcastPkts": 0,
        "ifInOctets": 0,
        "ifInUcastPkts": 0,
        "ifInUnknownProtos": 0,
        "ifIndex": 1007,
        "ifLastChange": 3300,
        "ifMtu": 1500,
        "ifName": "7",
        "ifOperStatus": 2,
        "ifOutDiscards": 0,
        "ifOutErrors": 0,
        "ifOutNUcastPkts": 0,
        "ifOutOctets": 0,
        "ifOutQLen": 0,
        "ifOutUcastPkts": 0,
        "ifPhysAddress": "00:04:96:97:e9:ee",
        "ifSpecific": "1.3.6.1",
        "ifSpeed": 0,
        "ifType": 6
      },
      {
        "dot1dBasePortIfIndex": 1008,
        "ifAdminStatus": 1,
        "ifDescr": "8",
        "ifInDiscards": 0,
        "ifInErrors": 0,
        "ifInNUcastPkts": 0,
        "ifInOctets": 0,
        "ifInUcastPkts": 0,
        "ifInUnknownProtos": 0,
        "ifIndex": 1008,
        "ifLastChange": 3300,
        "ifMtu": 1500,
        "ifName": "8",
        "ifOperStatus": 2,
        "ifOutDiscards": 0,
        "ifOutErrors": 0,
        "ifOutNUcastPkts": 0,
        "ifOutOctets": 0,
        "ifOutQLen": 0,
        "ifOutUcastPkts": 0,
        "ifPhysAddress": "00:04:96:97:e9:ee",
        "ifSpecific": "1.3.6.1",
        "ifSpeed": 0,
        "ifType": 6
      },
      {
        "dot1dBasePortIfIndex": 1009,
        "ifAdminStatus": 1,
        "ifDescr": "9",
        "ifInDiscards": 0,
        "ifInErrors": 0,
        "ifInNUcastPkts": 0,
        "ifInOctets": 0,
        "ifInUcastPkts": 0,
        "ifInUnknownProtos": 0,
        "ifIndex": 1009,
        "ifLastChange": 3300,
        "ifMtu": 1500,
        "ifName": "9",
        "ifOperStatus": 2,
        "ifOutDiscards": 0,
        "ifOutErrors": 0,
        "ifOutNUcastPkts": 0,
        "ifOutOctets": 0,
        "ifOutQLen": 0,
        "ifOutUcastPkts": 0,
        "ifPhysAddress": "00:04:96:97:e9:ee",
        "ifSpecific": "1.3.6.1",
        "ifSpeed": 0,
        "ifType": 6
      },
      {
        "dot1dBasePortIfIndex": 1010,
        "ifAdminStatus": 1,
        "ifDescr": "10",
        "ifInDiscards": 0,
        "ifInErrors": 0,
        "ifInNUcastPkts": 100896,
        "ifInOctets": 14073179,
        "ifInUcastPkts": 6523,
        "ifInUnknownProtos": 0,
        "ifIndex": 1010,
        "ifLastChange": 4000,
        "ifMtu": 1500,
        "ifName": "10",
        "ifOperStatus": 1,
        "ifOutDiscards": 0,
        "ifOutErrors": 0,
        "ifOutNUcastPkts": 6306,
        "ifOutOctets": 2491190,
        "ifOutQLen": 0,
        "ifOutUcastPkts": 6758,
        "ifPhysAddress": "00:04:96:97:e9:ee",
        "ifSpecific": "1.3.6.1",
        "ifSpeed": 1000000000,
        "ifType": 6
      },
      {
        "dot1dBasePortIfIndex": 1011,
        "ifAdminStatus": 1,
        "ifDescr": "11",
        "ifInDiscards": 0,
        "ifInErrors": 0,
        "ifInNUcastPkts": 100894,
        "ifInOctets": 14072591,
        "ifInUcastPkts": 6522,
        "ifInUnknownProtos": 0,
        "ifIndex": 1011,
        "ifLastChange": 4000,
        "ifMtu": 1500,
        "ifName": "11",
        "ifOperStatus": 1,
        "ifOutDiscards": 0,
        "ifOutErrors": 0,
        "ifOutNUcastPkts": 6306,
        "ifOutOctets": 2438668,
        "ifOutQLen": 0,
        "ifOutUcastPkts": 6523,
        "ifPhysAddress": "00:04:96:97:e9:ee",
        "ifSpecific": "1.3.6.1",
        "ifSpeed": 1000000000,
        "ifType": 6
      },
      {
        "dot1dBasePortIfIndex": 1012,
        "ifAdminStatus": 1,
        "ifDescr": "12",
        "ifInDiscards": 0,
        "ifInErrors": 0,
        "ifInNUcastPkts": 100897,
        "ifInOctets": 14024470,
        "ifInUcastPkts": 6305,
        "ifInUnknownProtos": 0,
        "ifIndex": 1012,
        "ifLastChange": 4000,
        "ifMtu": 1500,
        "ifName": "12",
        "ifOperStatus": 1,
        "ifOutDiscards": 0,
        "ifOutErrors": 0,
        "ifOutNUcastPkts": 6307,
        "ifOutOctets": 2491207,
        "ifOutQLen": 0,
        "ifOutUcastPkts": 6757,
        "ifPhysAddress": "00:04:96:97:e9:ee",
        "ifSpecific": "1.3.6.1",
        "ifSpeed": 1000000000,
        "ifType": 6
      },
      {
        "dot1dBasePortIfIndex": 1013,
        "ifAdminStatus": 1,
        "ifDescr": "13",
        "ifInDiscards": 0,
        "ifInErrors": 0,
        "ifInNUcastPkts": 0,
        "ifInOctets": 0,
        "ifInUcastPkts": 0,
        "ifInUnknownProtos": 0,
        "ifIndex": 1013,
        "ifLastChange": 3300,
        "ifMtu": 1500,
        "ifName": "13",
        "ifOperStatus": 2,
        "ifOutDiscards": 0,
        "ifOutErrors": 0,
        "ifOutNUcastPkts": 0,
        "ifOutOctets": 0,
        "ifOutQLen": 0,
        "ifOutUcastPkts": 0,
        "ifPhysAddress": "00:04:96:97:e9:ee",
        "ifSpecific": "1.3.6.1",
        "ifSpeed": 0,
        "ifType": 6
      },
      {
        "dot1dBasePortIfIndex": 1014,
        "ifAdminStatus": 1,
        "ifDescr": "14",
        "ifInDiscards": 0,
        "ifInErrors": 0,
        "ifInNUcastPkts": 0,
        "ifInOctets": 0,
        "ifInUcastPkts": 0,
        "ifInUnknownProtos": 0,
        "ifIndex": 1014,
        "ifLastChange": 3300,
        "ifMtu": 1500,
        "ifName": "14",
        "ifOperStatus": 2,
        "ifOutDiscards": 0,
        "ifOutErrors": 0,
        "ifOutNUcastPkts": 0,
        "ifOutOctets": 0,
        "ifOutQLen": 0,
        "ifOutUcastPkts": 0,
        "ifPhysAddress": "00:04:96:97:e9:ee",
        "ifSpecific": "1.3.6.1",
        "ifSpeed": 0,
        "ifType": 6
      },
      {
        "dot1dBasePortIfIndex": 1015,
        "ifAdminStatus": 1,
        "ifDescr": "15",
        "ifInDiscards": 0,
        "ifInErrors": 0,
        "ifInNUcastPkts": 0,
        "ifInOctets": 0,
        "ifInUcastPkts": 0,
        "ifInUnknownProtos": 0,
        "ifIndex": 1015,
        "ifLastChange": 3300,
        "ifMtu": 1500,
        "ifName": "15",
        "ifOperStatus": 2,
        "ifOutDiscards": 0,
        "ifOutErrors": 0,
        "ifOutNUcastPkts": 0,
        "ifOutOctets": 0,
        "ifOutQLen": 0,
        "ifOutUcastPkts": 0,
        "ifPhysAddress": "00:04:96:97:e9:ee",
        "ifSpecific": "1.3.6.1",
        "ifSpeed": 0,
        "ifType": 6
      },
      {
        "dot1dBasePortIfIndex": 1016,
        "ifAdminStatus": 1,
        "ifDescr": "16",
        "ifInDiscards": 0,
        "ifInErrors": 0,
        "ifInNUcastPkts": 0,
        "ifInOctets": 0,
        "ifInUcastPkts": 0,
        "ifInUnknownProtos": 0,
        "ifIndex": 1016,
        "ifLastChange": 3300,
        "ifMtu": 1500,
        "ifName": "16",
        "ifOperStatus": 2,
        "ifOutDiscards": 0,
        "ifOutErrors": 0,
        "ifOutNUcastPkts": 0,
        "ifOutOctets": 0,
        "ifOutQLen": 0,
        "ifOutUcastPkts": 0,
        "ifPhysAddress": "00:04:96:97:e9:ee",
        "ifSpecific": "1.3.6.1",
        "ifSpeed": 0,
        "ifType": 6
      },
      {
        "dot1dBasePortIfIndex": 1017,
        "ifAdminStatus": 1,
        "ifDescr": "17",
        "ifInDiscards": 0,
        "ifInErrors": 0,
        "ifInNUcastPkts": 0,
        "ifInOctets": 0,
        "ifInUcastPkts": 0,
        "ifInUnknownProtos": 0,
        "ifIndex": 1017,
        "ifLastChange": 3300,
        "ifMtu": 1500,
        "ifName": "17",
        "ifOperStatus": 2,
        "ifOutDiscards": 0,
        "ifOutErrors": 0,
        "ifOutNUcastPkts": 0,
        "ifOutOctets": 0,
        "ifOutQLen": 0,
        "ifOutUcastPkts": 0,
        "ifPhysAddress": "00:04:96:97:e9:ee",
        "ifSpecific": "1.3.6.1",
        "ifSpeed": 0,
        "ifType": 6
      },
      {
        "dot1dBasePortIfIndex": 1018,
        "ifAdminStatus": 1,
        "ifDescr": "18",
        "ifInDiscards": 0,
        "ifInErrors": 0,
        "ifInNUcastPkts": 0,
        "ifInOctets": 0,
        "ifInUcastPkts": 0,
        "ifInUnknownProtos": 0,
        "ifIndex": 1018,
        "ifLastChange": 3300,
        "ifMtu": 1500,
        "ifName": "18",
        "ifOperStatus": 2,
        "ifOutDiscards": 0,
        "ifOutErrors": 0,
        "ifOutNUcastPkts": 0,
        "ifOutOctets": 0,
        "ifOutQLen": 0,
        "ifOutUcastPkts": 0,
        "ifPhysAddress": "00:04:96:97:e9:ee",
        "ifSpecific": "1.3.6.1",
        "ifSpeed": 0,
        "ifType": 6
      },
      {
        "dot1dBasePortIfIndex": 1019,
        "ifAdminStatus": 1,
        "ifDescr": "19",
        "ifInDiscards": 0,
        "ifInErrors": 0,
        "ifInNUcastPkts": 0,
        "ifInOctets": 0,
        "ifInUcastPkts": 0,
        "ifInUnknownProtos": 0,
        "ifIndex": 1019,
        "ifLastChange": 3300,
        "ifMtu": 1500,
        "ifName": "19",
        "ifOperStatus": 2,
        "ifOutDiscards": 0,
        "ifOutErrors": 0,
        "ifOutNUcastPkts": 0,
        "ifOutOctets": 0,
        "ifOutQLen": 0,
        "ifOutUcastPkts": 0,
        "ifPhysAddress": "00:04:96:97:e9:ee",
        "ifSpecific": "1.3.6.1",
        "ifSpeed": 0,
        "ifType": 6
      },
      {
        "dot1dBasePortIfIndex": 1020,
        "ifAdminStatus": 1,
        "ifDescr": "20",
        "ifInDiscards": 0,
        "ifInErrors": 0,
        "ifInNUcastPkts": 100897,
        "ifInOctets": 14048497,
        "ifInUcastPkts": 6412,
        "ifInUnknownProtos": 0,
        "ifIndex": 1020,
        "ifLastChange": 4000,
        "ifMtu": 1500,
        "ifName": "20",
        "ifOperStatus": 1,
        "ifOutDiscards": 0,
        "ifOutErrors": 0,
        "ifOutNUcastPkts": 6309,
        "ifOutOctets": 2390205,
        "ifOutQLen": 0,
        "ifOutUcastPkts": 6305,
        "ifPhysAddress": "00:04:96:97:e9:ee",
        "ifSpecific": "1.3.6.1",
        "ifSpeed": 1000000000,
        "ifType": 6
      },
      {
        "dot1dBasePortIfIndex": 1021,
        "ifAdminStatus": 1,
        "ifDescr": "21",
        "ifInDiscards": 0,
        "ifInErrors": 0,
        "ifInNUcastPkts": 100893,
        "ifInOctets": 14125285,
        "ifInUcastPkts": 6757,
        "ifInUnknownProtos": 0,
        "ifIndex": 1021,
        "ifLastChange": 4200,
        "ifMtu": 1500,
        "ifName": "21",
        "ifOperStatus": 1,
        "ifOutDiscards": 0,
        "ifOutErrors": 0,
        "ifOutNUcastPkts": 6306,
        "ifOutOctets": 2389836,
        "ifOutQLen": 0,
        "ifOutUcastPkts": 6305,
        "ifPhysAddress": "00:04:96:97:e9:ee",
        "ifSpecific": "1.3.6.1",
        "ifSpeed": 1000000000,
        "ifType": 6
      },
      {
        "dot1dBasePortIfIndex": 1022,
        "ifAdminStatus": 1,
        "ifDescr": "22",
        "ifInDiscards": 0,
        "ifInErrors": 0,
        "ifInNUcastPkts": 100893,
        "ifInOctets": 14048229,
        "ifInUcastPkts": 6413,
        "ifInUnknownProtos": 0,
        "ifIndex": 1022,
        "ifLastChange": 4200,
        "ifMtu": 1500,
        "ifName": "22",
        "ifOperStatus": 1,
        "ifOutDiscards": 0,
        "ifOutErrors": 0,
        "ifOutNUcastPkts": 6306,
        "ifOutOctets": 2464204,
        "ifOutQLen": 0,
        "ifOutUcastPkts": 6637,
        "ifPhysAddress": "00:04:96:97:e9:ee",
        "ifSpecific": "1.3.6.1",
        "ifSpeed": 1000000000,
        "ifType": 6
      },
      {
        "dot1dBasePortIfIndex": 1023,
        "ifAdminStatus": 1,
        "ifDescr": "23",
        "ifInDiscards": 0,
        "ifInErrors": 0,
        "ifInNUcastPkts": 100894,
        "ifInOctets": 14072992,
        "ifInUcastPkts": 6523,
        "ifInUnknownProtos": 0,
        "ifIndex": 1023,
        "ifLastChange": 4200,
        "ifMtu": 1500,
        "ifName": "23",
        "ifOperStatus": 1,
        "ifOutDiscards": 0,
        "ifOutErrors": 0,
        "ifOutNUcastPkts": 6306,
        "ifOutOctets": 2414134,
        "ifOutQLen": 0,
        "ifOutUcastPkts": 6414,
        "ifPhysAddress": "00:04:96:97:e9:ee",
        "ifSpecific": "1.3.6.1",
        "ifSpeed": 1000000000,
        "ifType": 6
      },
      {
        "dot1dBasePortIfIndex": 1024,
        "ifAdminStatus": 1,
        "ifDescr": "24",
        "ifInDiscards": 0,
        "ifInErrors": 0,
        "ifInNUcastPkts": 100894,
        "ifInOctets": 14072992,
        "ifInUcastPkts": 6523,
        "ifInUnknownProtos": 0,
        "ifIndex": 1024,
        "ifLastChange": 4200,
        "ifMtu": 1500,
        "ifName": "24",
        "ifOperStatus": 1,
        "ifOutDiscards": 0,
        "ifOutErrors": 0,
        "ifOutNUcastPkts": 6306,
        "ifOutOctets": 2491084,
        "ifOutQLen": 0,
        "ifOutUcastPkts": 6757,
        "ifPhysAddress": "00:04:96:97:e9:ee",
        "ifSpecific": "1.3.6.1",
        "ifSpeed": 1000000000,
        "ifType": 6
      },
      {
        "dot1dBasePortIfIndex": 1025,
        "ifAdminStatus": 1,
        "ifDescr": "25",
        "ifInDiscards": 0,
        "ifInErrors": 0,
        "ifInNUcastPkts": 0,
        "ifInOctets": 0,
        "ifInUcastPkts": 0,
        "ifInUnknownProtos": 0,
        "ifIndex": 1025,
        "ifLastChange": 3300,
        "ifMtu": 1500,
        "ifName": "25",
        "ifOperStatus": 2,
        "ifOutDiscards": 0,
        "ifOutErrors": 0,
        "ifOutNUcastPkts": 0,
        "ifOutOctets": 0,
        "ifOutQLen": 0,
        "ifOutUcastPkts": 0,
        "ifPhysAddress": "00:04:96:97:e9:ee",
        "ifSpecific": "1.3.6.1",
        "ifSpeed": 0,
        "ifType": 6
      },
      {
        "dot1dBasePortIfIndex": 1026,
        "ifAdminStatus": 1,
        "ifDescr": "26",
        "ifInDiscards": 0,
        "ifInErrors": 0,
        "ifInNUcastPkts": 0,
        "ifInOctets": 0,
        "ifInUcastPkts": 0,
        "ifInUnknownProtos": 0,
        "ifIndex": 1026,
        "ifLastChange": 3300,
        "ifMtu": 1500,
        "ifName": "26",
        "ifOperStatus": 2,
        "ifOutDiscards": 0,
        "ifOutErrors": 0,
        "ifOutNUcastPkts": 0,
        "ifOutOctets": 0,
        "ifOutQLen": 0,
        "ifOutUcastPkts": 0,
        "ifPhysAddress": "00:04:96:97:e9:ee",
        "ifSpecific": "1.3.6.1",
        "ifSpeed": 0,
        "ifType": 6
      },
      {
        "dot1dBasePortIfIndex": 1027,
        "ifAdminStatus": 1,
        "ifDescr": "27",
        "ifInDiscards": 0,
        "ifInErrors": 0,
        "ifInNUcastPkts": 0,
        "ifInOctets": 0,
        "ifInUcastPkts": 0,
        "ifInUnknownProtos": 0,
        "ifIndex": 1027,
        "ifLastChange": 3300,
        "ifMtu": 1500,
        "ifName": "27",
        "ifOperStatus": 2,
        "ifOutDiscards": 0,
        "ifOutErrors": 0,
        "ifOutNUcastPkts": 0,
        "ifOutOctets": 0,
        "ifOutQLen": 0,
        "ifOutUcastPkts": 0,
        "ifPhysAddress": "00:04:96:97:e9:ee",
        "ifSpecific": "1.3.6.1",
        "ifSpeed": 0,
        "ifType": 6
      },
      {
        "dot1dBasePortIfIndex": 1028,
        "ifAdminStatus": 1,
        "ifDescr": "28",
        "ifInDiscards": 0,
        "ifInErrors": 0,
        "ifInNUcastPkts": 0,
        "ifInOctets": 0,
        "ifInUcastPkts": 0,
        "ifInUnknownProtos": 0,
        "ifIndex": 1028,
        "ifLastChange": 3300,
        "ifMtu": 1500,
        "ifName": "28",
        "ifOperStatus": 2,
        "ifOutDiscards": 0,
        "ifOutErrors": 0,
        "ifOutNUcastPkts": 0,
        "ifOutOctets": 0,
        "ifOutQLen": 0,
        "ifOutUcastPkts": 0,
        "ifPhysAddress": "00:04:96:97:e9:ee",
        "ifSpecific": "1.3.6.1",
        "ifSpeed": 0,
        "ifType": 6
      },
      {
        "dot1dBasePortIfIndex": 1029,
        "ifAdminStatus": 1,
        "ifDescr": "29",
        "ifInDiscards": 0,
        "ifInErrors": 0,
        "ifInNUcastPkts": 0,
        "ifInOctets": 0,
        "ifInUcastPkts": 0,
        "ifInUnknownProtos": 0,
        "ifIndex": 1029,
        "ifLastChange": 3300,
        "ifMtu": 1500,
        "ifName": "29",
        "ifOperStatus": 2,
        "ifOutDiscards": 0,
        "ifOutErrors": 0,
        "ifOutNUcastPkts": 0,
        "ifOutOctets": 0,
        "ifOutQLen": 0,
        "ifOutUcastPkts": 0,
        "ifPhysAddress": "00:04:96:97:e9:ee",
        "ifSpecific": "1.3.6.1",
        "ifSpeed": 0,
        "ifType": 6
      },
      {
        "dot1dBasePortIfIndex": 1030,
        "ifAdminStatus": 1,
        "ifDescr": "30",
        "ifInDiscards": 0,
        "ifInErrors": 0,
        "ifInNUcastPkts": 0,
        "ifInOctets": 0,
        "ifInUcastPkts": 0,
        "ifInUnknownProtos": 0,
        "ifIndex": 1030,
        "ifLastChange": 3300,
        "ifMtu": 1500,
        "ifName": "30",
        "ifOperStatus": 2,
        "ifOutDiscards": 0,
        "ifOutErrors": 0,
        "ifOutNUcastPkts": 0,
        "ifOutOctets": 0,
        "ifOutQLen": 0,
        "ifOutUcastPkts": 0,
        "ifPhysAddress": "00:04:96:97:e9:ee",
        "ifSpecific": "1.3.6.1",
        "ifSpeed": 0,
        "ifType": 6
      },
      {
        "dot1dBasePortIfIndex": 1031,
        "ifAdminStatus": 1,
        "ifDescr": "31",
        "ifInDiscards": 0,
        "ifInErrors": 189176,
        "ifInNUcastPkts": 0,
        "ifInOctets": 17025840,
        "ifInUcastPkts": 0,
        "ifInUnknownProtos": 0,
        "ifIndex": 1031,
        "ifLastChange": 18006900,
        "ifMtu": 1500,
        "ifName": "31",
        "ifOperStatus": 1,
        "ifOutDiscards": 0,
        "ifOutErrors": 0,
        "ifOutNUcastPkts": 100903,
        "ifOutOctets": 13749263,
        "ifOutQLen": 0,
        "ifOutUcastPkts": 3323,
        "ifPhysAddress": "00:04:96:97:e9:ee",
        "ifSpecific": "1.3.6.1",
        "ifSpeed": 4294967295,
        "ifType": 6
      },
      {
        "dot1dBasePortIfIndex": 1032,
        "ifAdminStatus": 1,
        "ifDescr": "32",
        "ifInDiscards": 0,
        "ifInErrors": 189175,
        "ifInNUcastPkts": 0,
        "ifInOctets": 17025750,
        "ifInUcastPkts": 0,
        "ifInUnknownProtos": 0,
        "ifIndex": 1032,
        "ifLastChange": 4100,
        "ifMtu": 1500,
        "ifName": "32",
        "ifOperStatus": 1,
        "ifOutDiscards": 0,
        "ifOutErrors": 0,
        "ifOutNUcastPkts": 100897,
        "ifOutOctets": 13747130,
        "ifOutQLen": 0,
        "ifOutUcastPkts": 3319,
        "ifPhysAddress": "00:04:96:97:e9:ee",
        "ifSpecific": "1.3.6.1",
        "ifSpeed": 4294967295,
        "ifType": 6
      },
      {
        "dot1dBasePortIfIndex": 1033,
        "ifAdminStatus": 1,
        "ifDescr": "33",
        "ifInDiscards": 0,
        "ifInErrors": 0,
        "ifInNUcastPkts": 0,
        "ifInOctets": 0,
        "ifInUcastPkts": 0,
        "ifInUnknownProtos": 0,
        "ifIndex": 1033,
        "ifLastChange": 3300,
        "ifMtu": 1500,
        "ifName": "33",
        "ifOperStatus": 6,
        "ifOutDiscards": 0,
        "ifOutErrors": 0,
        "ifOutNUcastPkts": 0,
        "ifOutOctets": 0,
        "ifOutQLen": 0,
        "ifOutUcastPkts": 0,
        "ifPhysAddress": "00:04:96:97:e9:ee",
        "ifSpecific": "1.3.6.1",
        "ifSpeed": 0,
        "ifType": 6
      },
      {
        "dot1dBasePortIfIndex": 1034,
        "ifAdminStatus": 1,
        "ifDescr": "34",
        "ifInDiscards": 0,
        "ifInErrors": 0,
        "ifInNUcastPkts": 0,
        "ifInOctets": 0,
        "ifInUcastPkts": 0,
        "ifInUnknownProtos": 0,
        "ifIndex": 1034,
        "ifLastChange": 3300,
        "ifMtu": 1500,
        "ifName": "34",
        "ifOperStatus": 6,
        "ifOutDiscards": 0,
        "ifOutErrors": 0,
        "ifOutNUcastPkts": 0,
        "ifOutOctets": 0,
        "ifOutQLen": 0,
        "ifOutUcastPkts": 0,
        "ifPhysAddress": "00:04:96:97:e9:ee",
        "ifSpecific": "1.3.6.1",
        "ifSpeed": 0,
        "ifType": 6
      },
      {
        "ifAdminStatus": 1,
        "ifDescr": "Management Port",
        "ifInDiscards": 0,
        "ifInErrors": 79,
        "ifInNUcastPkts": 0,
        "ifInOctets": 53502483,
        "ifInUcastPkts": 0,
        "ifInUnknownProtos": 0,
        "ifIndex": 1035,
        "ifLastChange": 3900,
        "ifMtu": 1500,
        "ifName": "Management",
        "ifOperStatus": 1,
        "ifOutDiscards": 0,
        "ifOutErrors": 0,
        "ifOutNUcastPkts": 0,
        "ifOutOctets": 2067920,
        "ifOutQLen": 0,
        "ifOutUcastPkts": 0,
        "ifPhysAddress": "00:04:96:97:e9:ee",
        "ifSpecific": "1.3.6.1",
        "ifSpeed": 1000000000,
        "ifType": 6
      },
      {
        "ifAdminStatus": 1,
        "ifDescr": "VirtualRouter0",
        "ifInDiscards": 0,
        "ifInErrors": 0,
        "ifInNUcastPkts": 0,
        "ifInOctets": 0,
        "ifInUcastPkts": 0,
        "ifInUnknownProtos": 0,
        "ifIndex": 1000001,
        "ifLastChange": 1700,
        "ifMtu": 0,
        "ifName": "VirtualRouter0",
        "ifOperStatus": 1,
        "ifOutDiscards": 0,
        "ifOutErrors": 0,
        "ifOutNUcastPkts": 0,
        "ifOutOctets": 0,
        "ifOutQLen": 0,
        "ifOutUcastPkts": 0,
        "ifPhysAddress": "",
        "ifSpecific": "1.3.6.1",
        "ifSpeed": 0,
        "ifType": 53
      },
      {
        "ifAdminStatus": 1,
        "ifDescr": "VirtualRouter1",
        "ifInDiscards": 0,
        "ifInErrors": 0,
        "ifInNUcastPkts": 0,
        "ifInOctets": 0,
        "ifInUcastPkts": 0,
        "ifInUnknownProtos": 0,
        "ifIndex": 1000002,
        "ifLastChange": 1700,
        "ifMtu": 0,
        "ifName": "VirtualRouter1",
        "ifOperStatus": 1,
        "ifOutDiscards": 0,
        "ifOutErrors": 0,
        "ifOutNUcastPkts": 0,
        "ifOutOctets": 0,
        "ifOutQLen": 0,
        "ifOutUcastPkts": 0,
        "ifPhysAddress": "",
        "ifSpecific": "1.3.6.1",
        "ifSpeed": 0,
        "ifType": 53
      },
      {
        "ifAdminStatus": 1,
        "ifDescr": "VirtualRouter2",
        "ifInDiscards": 0,
        "ifInErrors": 0,
        "ifInNUcastPkts": 0,
        "ifInOctets": 0,
        "ifInUcastPkts": 0,
        "ifInUnknownProtos": 0,
        "ifIndex": 1000003,
        "ifLastChange": 1700,
        "ifMtu": 0,
        "ifName": "VirtualRouter2",
        "ifOperStatus": 1,
        "ifOutDiscards": 0,
        "ifOutErrors": 0,
        "ifOutNUcastPkts": 0,
        "ifOutOctets": 0,
        "ifOutQLen": 0,
        "ifOutUcastPkts": 0,
        "ifPhysAddress": "",
        "ifSpecific": "1.3.6.1",
        "ifSpeed": 0,
        "ifType": 53
      },
      {
        "ifAdminStatus": 1,
        "ifDescr": "VLAN 00001 (Default)",
        "ifInDiscards": 0,
        "ifInErrors": 0,
        "ifInNUcastPkts": 0,
        "ifInOctets": 0,
        "ifInUcastPkts": 0,
        "ifInUnknownProtos": 0,
        "ifIndex": 1000004,
        "ifLastChange": 4000,
        "ifMtu": 1500,
        "ifName": "VLAN 00001 (Default)",
        "ifOperStatus": 1,
        "ifOutDiscards": 0,
        "ifOutErrors": 0,
        "ifOutNUcastPkts": 0,
        "ifOutOctets": 0,
        "ifOutQLen": 0,
        "ifOutUcastPkts": 0,
        "ifPhysAddress": "",
        "ifSpecific": "1.3.6.1",
        "ifSpeed": 0,
        "ifType": 53
      },
      {
        "ifAdminStatus": 1,
        "ifDescr": "VLAN 04095 (Mgmt)",
        "ifInDiscards": 0,
        "ifInErrors": 0,
        "ifInNUcastPkts": 0,
        "ifInOctets": 0,
        "ifInUcastPkts": 0,
        "ifInUnknownProtos": 0,
        "ifIndex": 1000005,
        "ifLastChange": 3900,
        "ifMtu": 1500,
        "ifName": "VLAN 04095 (Mgmt)",
        "ifOperStatus": 1,
        "ifOutDiscards": 0,
        "ifOutErrors": 0,
        "ifOutNUcastPkts": 0,
        "ifOutOctets": 0,
        "ifOutQLen": 0,
        "ifOutUcastPkts": 0,
        "ifPhysAddress": "",
        "ifSpecific": "1.3.6.1",
        "ifSpeed": 0,
        "ifType": 53
      },
      {
        "ifAdminStatus": 1,
        "ifDescr": "Mgmt rtif(10.68.67.93/24)",
        "ifInDiscards": 0,
        "ifInErrors": 0,
        "ifInNUcastPkts": 0,
        "ifInOctets": 0,
        "ifInUcastPkts": 0,
        "ifInUnknownProtos": 0,
        "ifIndex": 1000006,
        "ifLastChange": 4100,
        "ifMtu": 1500,
        "ifName": "Mgmt rtif(10.68.67.93/24)",
        "ifOperStatus": 1,
        "ifOutDiscards": 0,
        "ifOutErrors": 0,
        "ifOutNUcastPkts": 0,
        "ifOutOctets": 0,
        "ifOutQLen": 0,
        "ifOutUcastPkts": 0,
        "ifPhysAddress": "00:04:96:97:e9:ee",
        "ifSpecific": "1.3.6.1",
        "ifSpeed": 0,
        "ifType": 53
      }
    ],
    "license": {
      "effectiveLicense": "Advanced Edge",
      "enabledLicense": "Advanced Edge",
      "featurePacks": [
        "DirectAttach"
      ],
      "portCapacityLicense": ""
    },
    "macAddr": "00:04:96:97:E9:EE",
    "mgmtIpAddr": "10.68.67.93",
    "mgmtPort": "0",
    "operatingSystem": "ExtremeXOS",
    "ports": [
      {
        "portList": [
          "mgmt-1"
        ],
        "portSpeed": 100,
        "portType": "mgmt"
      },
      {
        "portList": [
          "25",
          "26",
          "27",
          "28"
        ],
        "portSpeed": 0,
        "portType": "access"
      },
      {
        "portList": [
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24"
        ],
        "portSpeed": 1000,
        "portType": "access"
      },
      {
        "portList": [
          "29",
          "30",
          "31",
          "32",
          "33",
          "34"
        ],
        "portSpeed": 10000,
        "portType": "uplink"
      }
    ],
    "serialNumber": "1405G-00125",
    "sysContact": "support@extremenetworks.com, +1 888 257 3000",
    "sysDescr": "ExtremeXOS (X460G2-24t-10G4) version 22.6.0.20 xos_22.6 by dhammers on Wed Aug 8 17:10:39 EDT 2018",
    "sysName": "X460G2-24t-10G4",
    "sysObjectID": "1.3.6.1.4.1.1916.2.197",
    "sysUpTime": 18829200
  }
}`
)

func main() {
    var jsonData map[string]interface{}
    _ = json.Unmarshal([]byte(jsonStuff) , &jsonData)

    abc := jsonData["deviceInfo"].(map[string]interface{})
    def := abc["ports"].([]interface{})
    ghi := def[3].(map[string]interface{})
    jkl := ghi["portList"].([]interface{})

    for _, port := range jkl {
        fmt.Println(port)
    }

    return 
}
