version: '3.5'

services:
  my-server:
    build: ./server
    volumes:
      - ./server:/usr/src/app
    networks:
      - my-network
    ports:
      - 5001:5000

  my-client:
    build: ./client
    ports:
      - 8080:80
    networks:
      - my-network    
    depends_on:
      - my-server

networks:
  my-network:
    name: ihz-net