version: '3'

services:
  my-server:
    build: ./server
    volumes:
      - ./server:/usr/src/app
    ports:
      - 5001:5000

  my-client:
    build: ./client
    ports:
      - 8080:80
    depends_on:
      - my-server